---
title: "Getting and Cleaning Data assignment"
author: "Oleksii Yehorchenkov"
date: "30 11 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

This assignment is based on materials from Coursera course [Exploratory Data Analysis](https://www.coursera.org/learn/exploratory-data-analysis/home/welcome)

## Introduction

Fine particulate matter (PM2.5) is an ambient air pollutant for which there is strong evidence that it is harmful to human health. In the United States, the Environmental Protection Agency (EPA) is tasked with setting national ambient air quality standards for fine PM and for tracking the emissions of this pollutant into the atmosphere. Approximatly every 3 years, the EPA releases its database on emissions of PM2.5. This database is known as the National Emissions Inventory (NEI). You can read more information about the NEI at the EPA National Emissions Inventory web site.

For each year and for each type of PM source, the NEI records how many tons of PM2.5 were emitted from that source over the course of the entire year. The data that you will use for this assignment are for 1999, 2002, 2005, and 2008.

## Data

The data for this assignment could be downloaded by the [link](https://www.dropbox.com/s/fey54ngk8g4z6rr/exdata_data_NEI_data.zip?dl=0):

The zip file contains two files:

**PM2.5 Emissions Data** (`summarySCC_PM25.rds`): This file contains a data frame with all of the PM2.5 emissions data for 1999, 2002, 2005, and 2008. For each year, the table contains number of tons of PM2.5 emitted from a specific type of source for the entire year.

- **fips**: A five-digit number (represented as a string) indicating the U.S. county
- **SCC**: The name of the source as indicated by a digit string (see source code classification table)
- **Pollutant**: A string indicating the pollutant
- **Emissions**: Amount of PM2.5 emitted, in tons
- **type**: The type of source (point, non-point, on-road, or non-road)
- **year**: The year of emissions recorded

**Source Classification Code Table** (`Source_Classification_Code.rds`): This table provides a mapping from the SCC digit strings in the Emissions table to the actual name of the PM2.5 source. The sources are categorized in a few different ways from more general to more specific and you may choose to explore whatever categories you think are most useful. For example, source “10100101” is known as “Ext Comb /Electric Gen /Anthracite Coal /Pulverized Coal”.

You can read each of the two files using the `readRDS()` function in R. For example, reading in each file can be done with the following code:

```
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
```
## Questions

You must address the following questions and tasks in your exploratory analysis. For each question/task you will need to make a single **bar** plot. You can use any plotting system in R to make your plot.

1. Have total emissions from PM2.5 decreased in the United States from 1999 to 2008? Make a plot showing the **total** PM2.5 emission from all sources for each of the years 1999, 2002, 2005, and 2008.
2. Have total emissions from PM2.5 decreased in the **Baltimore City**, Maryland (`fips == "24510"`) from 1999 to 2008?
3. Of the four types of sources indicated by the `type` (point, nonpoint, onroad, nonroad) variable, which of these four sources have seen decreases in emissions from 1999–2008 for **Baltimore City**? Which have seen increases in emissions from 1999–2008?
4. Across the United States, how have emissions from coal combustion-related sources changed from 1999–2008?
5. How have emissions from motor vehicle sources changed from 1999–2008 in **Baltimore City** (EI.Sector starts from "Mobile")?
6. Compare emissions from motor vehicle sources in Baltimore City with emissions from motor vehicle sources in **Los Angeles County**, California (`fips == "06037"`). Which city has seen greater changes over time in motor vehicle emissions?

#Libraries

```
library(plyr)
library(ggplot2)
```
# Just checking the data...
```
str(NEI)
str(SCC)

SCC$EI.Sector

```

# Question 1
```
total_data <- aggregate(Emissions ~ year,NEI, sum)
barplot(
  (total_data$Emissions)/10^3,
  names.arg=total_data$year,
  xlab="Year",
  ylab="Emissions (10^3 Tons)",
  main="Total PM2.5 Emissions",
  col="blue"
)

```

# Total emissions decreased between years 1999 and 2008

# Question 2
```
baltimore_NEI <- NEI[NEI$fips=="24510",]
baltimore_total <- aggregate(Emissions ~ year, baltimore_NEI,sum)

barplot(
  (baltimore_total$Emissions)/10^3,
  names.arg=baltimore_total$year,
  xlab="Year",
  ylab="Emissions (10^3 Tons)",
  main="Total Emissions of Baltimore City",
  col="blue"
)

```
# Total emissions have decreased in Baltimore City from 1999 to 2008

# Question 3
```
ggplot <- ggplot(baltimore_NEI,aes(factor(year),Emissions,fill=type)) +
  geom_bar(stat="identity") +
  facet_grid(.~type) +
  theme_bw() + guides(fill=FALSE)+
  labs(x="year", y="Emissions (Tons)") + 
  labs(title="Emissions of Baltimore City by Source Type")

print(ggplot)

```

# Question 4

```
coal_data <- grepl("coal", SCC$SCC.Level.Four, ignore.case=TRUE) 
combustion_data <- grepl("comb", SCC$SCC.Level.One, ignore.case=TRUE)
coal_combustion <- (combustion_data & coal_data)
combustion_SCC <- SCC[combustion_data,]$SCC
combustion_NEI <- NEI[NEI$SCC %in% combustion_SCC,]

ggplot <- ggplot(combustion_NEI,aes(factor(year),Emissions/10^3)) +
  geom_bar(stat="identity",fill="blue",width=0.5) +
  theme_bw() +  guides(fill=FALSE) +
  labs(x="year", y="Emissions (10^3 Tons)") + 
  labs(title="Coal Combustion Related Emissions from 1999-2008")

print(ggplot)

```

# Question 5
```
mobile_vehicles <- grepl("mobile", SCC$EI.Sector, ignore.case=TRUE)
mobile_SCC <- SCC[mobile_vehicles,]$SCC
mobile_NEI <- NEI[NEI$SCC %in% mobile_SCC,]

baltimore_mobile_NEI <- mobile_NEI[mobile_NEI$fips==24510,]

ggplot <- ggplot(baltimore_mobile_NEI,aes(factor(year),Emissions)) +
  geom_bar(stat="identity",fill="blue",width=0.5) +
  theme_bw() +  guides(fill=FALSE) +
  labs(x="year", y="Emission (10^5 Tons)") + 
  labs(title="Motor Vehicles Related Emissions from 1999-2008")

print(ggplot)

```

# Question 6
```
mobile_Baltimore_NEI <- mobile_NEI[mobile_NEI$fips == 24510,]
mobile_Baltimore_NEI$city <- "Baltimore City"
mobile_LA_NEI <- mobile_NEI[mobile_NEI$fips=="06037",]
mobile_LA_NEI$city <- "Los Angeles County"
balt_la_NEI <- rbind(mobile_Baltimore_NEI,mobile_LA_NEI)

ggp <- ggplot(balt_la_NEI, aes(x=factor(year), y=Emissions, fill=city)) +
 geom_bar(aes(fill=year),stat="identity") +
 facet_grid(.~city) +
 guides(fill=FALSE) + theme_bw() +
 labs(x="year", y="Emission (10^3 Tons)") + 
 labs(title="Motor Vehicle Source Emissions in Baltimore & LA, 1999-2008")
 
print(ggp)

```